# 应用端口号
server:
  port: 8767

# 配置spring的应用名
spring:
  application:
    name: eureka3

# 默认不注册自己
eureka:
  client:
    register-with-eureka: false

    # 手动配置地址
    service-url:
      defaultZone: http://eureka2:8766/eureka/,http://eureka:8765/eureka/