# 应用端口号
server:
  port: 8001

# 配置spring的应用名
spring:
  application:
    name: eureka

# 默认不注册自己
eureka:
  client:
    register-with-eureka: false

    # 手动配置地址
    service-url:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka/



  server:
    enable-self-preservation: false #关闭自我保护模式(缺省为打开)
    eviction-interval-timer-in-ms: 1000 #续期时间,即扫描失效服务的间隔时间(毫秒)