# 应用端口号
server:
  port: 8002

# 配置spring的应用名
spring:
  application:
    name: eureka2

# 默认不注册自己
eureka:
  client:
    register-with-eureka: false

    # 手动配置地址
    service-url:
      defaultZone: http://eureka3:8003/eureka/,http://eureka:8001/eureka/