eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka/,http://eureka:8001/eureka/
  instance:
    instance-id: dehanClientconsume
    prefer-ip-address: true #访问路径显示IP地址
spring:
  application:
    name: eureka-client-consum

#应用端口号
server:
  port: 8119


feign:
  hystrix:
    enabled: true #开启Hystrix  熔断和降级处理支持